// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/tvmaze-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"aka | alternate_list | cast | cast_credit | cast_member | crew | crew_credit | crew_member | episode | guest_cast_credit | image | person | schedule | scheduled_episode | search | season | show | update"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.TvmazeSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "tvmaze_list",
		Description: "List records from Tvmaze. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "tvmaze_load",
		Description: "Load a single record from Tvmaze. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.TvmazeSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.TvmazeSDK, name string) (sdk.TvmazeEntity, error) {
	switch strings.ToLower(name) {
	case "aka":
		return client.Aka(nil), nil
	case "alternate_list":
		return client.AlternateList(nil), nil
	case "cast":
		return client.Cast(nil), nil
	case "cast_credit":
		return client.CastCredit(nil), nil
	case "cast_member":
		return client.CastMember(nil), nil
	case "crew":
		return client.Crew(nil), nil
	case "crew_credit":
		return client.CrewCredit(nil), nil
	case "crew_member":
		return client.CrewMember(nil), nil
	case "episode":
		return client.Episode(nil), nil
	case "guest_cast_credit":
		return client.GuestCastCredit(nil), nil
	case "image":
		return client.Image(nil), nil
	case "person":
		return client.Person(nil), nil
	case "schedule":
		return client.Schedule(nil), nil
	case "scheduled_episode":
		return client.ScheduledEpisode(nil), nil
	case "search":
		return client.Search(nil), nil
	case "season":
		return client.Season(nil), nil
	case "show":
		return client.Show(nil), nil
	case "update":
		return client.Update(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
